<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pdf_converter"
 *
 * Auto generated by Extension Builder 2018-09-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Page to Pdf',
    'description' => 'a backend module that converts a standard page in page tree to pdf.',
    'category' => 'module',
    'author' => 'Kasim Sabah',
    'author_email' => 'kasim,sm@pitsolutions.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => 
    array(
        'psr-4' => array('PITS\\PdfConverter\\' => 'Classes'),
        'classmap' => array(
            'Libraries'
        )
    )
];
